version: '2'

services:
    nginx:
        container_name: TmsNginx
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - "80:80"
            - "444:443"
        volumes_from:
            - appdata
            - cachedata
        environment:
            VIRTUAL_HOST: "tms.dev"
            NGINX_CONF: "dev"
        depends_on:
            - php-fpm
        links:
            - "php-fpm:TmsPHP"
        networks:
            - TmsNet

    php-fpm:
        container_name: TmsPHP
        build:
            context: .
            dockerfile: php/Dockerfile
        volumes_from:
            - appdata
            - cachedata
        depends_on:
          - mysql
          #- beanstalkd
          - appdata
        links:
            - "mysql:TmsMysql"
            #- "beanstalkd:TmsBeanstalkd"
        networks:
            - TmsNet

    appdata:
        container_name: TmsApp
        build:
            context: .
            dockerfile: appdata/Dockerfile
        volumes:
            - ./appcode:/var/www/html
        networks:
            - TmsNet

    cachedata:
        container_name: TmsCacheData
        build:
            context: .
            dockerfile: cachedata/Dockerfile
        networks:
            - TmsNet

    mysql:
        container_name: TmsMysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: '1'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: '1'
            MYSQL_DATABASE: 'tms'
        ports:
            - "3306:3307"
        networks:
            - TmsNet

    # redis:
    #     container_name: TmsRedis
    #     image: redis:3.2.0
    #     ports:
    #         - "6380:6379"

    # beanstalkd:
    #     container_name: TmsBeanstalkd
    #     image: schickling/beanstalkd
    #     ports:
    #         - "11300:11300"

    # beanstalkd-console:
    #     container_name: TmsBeanstalkdConsole
    #     image: agaveapi/beanstalkd-console
    #     links:
    #         - "beanstalkd:TmsBeanstalkd"
    #     ports:
    #         - "8088:80"

networks:
    TmsNet:
        driver: bridge
        ipam:
            config:
            - subnet: 10.10.10.0/24
              gateway: 10.10.10.1
